### ISSUE TITLE
Dynamic schedule tab

### ISSUE THREAD

**Issue by rgbayrak** [ohbm/osr2022#16]
Replace the static schedule with a more dynamic schedule tab. This page will contain direct links to relevant info:
- emergent sessions will have a link for registration that will be pushed during the conference (so create placeholder)
- panel sessions will have a link to their info page (https://ohbm.github.io/osr2022/panel), perhaps the section within that page
- streaming info (e.g. crowdcast links) relevant to a particular session will be pushed during the conference (so create placeholder)
- implement the schedule to eventable (https://add.eventable.com/free-add-to-calendar-button) 
- 'add to calendar' option using eventable

See https://ohbm.github.io/osr2020/schedule/ for inspiration.
Note that we are not trying to implement is a is but make it more user-friendly (less scrolls)

**Comment by rgbayrak** [comment]
Hey @cassgvp, I heard that you'd like to help us out with this. Let me know if you'd like to schedule a meeting with me to weed out details?

**Comment by rgbayrak** [comment]
@cassgvp did you want to meet for this? It is becoming a bit urgent at this point, else I will request help from volunteers. Please let me know.

**Comment by cassgvp** [comment]
Hi @rgbayrak - so sorry, I'm pretty swamped at the moment! I was going to offer to walk you through the code we had for 2020. Would this be helpful? I know you were looking for something slimmer / less scrolling.

**Comment by rgbayrak** [comment]
Yes! @RaphaelMeudec

**Comment by RaphaelMeudec** [comment]
Here is a quick proposition following what has been said around starting from the 2020 schedule page and making it less scroll-dependant. The idea is to have a menu where users click on the day they want to see, and only the schedule for the day would appear.

Let me know what are your opinions on this and how you would see the schedule appear for each day!

User clicks on June 20:

![image](https://user-images.githubusercontent.com/12402673/171909663-6ec71a40-88c0-499b-8fa2-f0f6f31b263b.png)

User clicks on June 22:

![image](https://user-images.githubusercontent.com/12402673/171909890-ec19b0a5-e9c7-46c7-a671-561df60a9511.png)

**Comment by rgbayrak** [comment]
I like the idea of tabs. We should have the component we have in the static schedule where we are OHBM to OSR comparison. 

I would like to add add to you calendar buttons for each event. Can you try with this button?

Embed this: 
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a28568622ac08962b8c7f" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-event="629a28568622ac08962b8c7f" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://plugins.eventable.com/eventable.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script', 'eventable-script');</script>

This button should have add to your calendar links for the events.

**Comment by rgbayrak** [comment]
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a28568622ac08962b8c7f" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-event="629a28568622ac08962b8c7f" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://plugins.eventable.com/eventable.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script', 'eventable-script');</script>
```

**Comment by RaphaelMeudec** [comment]
The add button works fine, we juste have to generate one for each day

**Comment by rgbayrak** [comment]
It will be one per event, since it has the streaming link. I am currently working on it, will send the whole list in 1 hour (?).

**Comment by rgbayrak** [comment]
**Challenges of Open Science in Developing Countries**
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a28568622ac08962b8c7f" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-event="629a28568622ac08962b8c7f" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://plugins.eventable.com/eventable.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script', 'eventable-script');</script>
```


**Open Publishing**
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a4a43a7c9374f60d948fd/" data-event="629a4a43a7c9374f60d948fd" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://plugins.eventable.com/eventable.js";fjs.parentNode.insertBefore(js, fjs);}}(document, "script", "eventable-script");</script>
```

**Open Code: 6 Myths Debunked**
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a4abd1fd9d50830ca3664/" data-event="629a4abd1fd9d50830ca3664" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://plugins.eventable.com/eventable.js";fjs.parentNode.insertBefore(js, fjs);}}(document, "script", "eventable-script");</script>
```

**Emerging Statistical Perspectives in Promoting Reproducible Research**
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a4b4210e33846f6e40e62/" data-event="629a4b4210e33846f6e40e62" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://plugins.eventable.com/eventable.js";fjs.parentNode.insertBefore(js, fjs);}}(document, "script", "eventable-script");</script>
```


**Social Bias in Machine Learning** 
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a4ba20de33e392ef7ff06/" data-event="629a4ba20de33e392ef7ff06" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://plugins.eventable.com/eventable.js";fjs.parentNode.insertBefore(js, fjs);}}(document, "script", "eventable-script");</script>
```


These can also go under the respective panel themes!

I will make buttons for the other session, but they will be later today.

**Comment by rgbayrak** [comment]
**Virtual Table Talk 1: Charting a career path after the PhD with Chao-Gan Yan**
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a4d12c3b6562f7c722622/" data-event="629a4d12c3b6562f7c722622" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://plugins.eventable.com/eventable.js";fjs.parentNode.insertBefore(js, fjs);}}(document, "script", "eventable-script");</script>
```

**Virtual Table Talk 2: Lab Culture with Mariam Aly**
```
<a href="https://add.eventable.com/events/629a28543ef85c3ac00e5e83/629a4dab3efc5d0717acbfa8/" data-event="629a4dab3efc5d0717acbfa8" class="eventable-link" target="_blank" data-key="629a28543ef85c3ac00e5e83" data-style="1">Add to Calendar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://plugins.eventable.com/eventable.js";fjs.parentNode.insertBefore(js, fjs);}}(document, "script", "eventable-script");</script>
```

**Comment by RaphaelMeudec** [comment]
Should I also add those "add to calendar" buttons to the [tabletalks](https://ohbm.github.io/osr2022/tabletalk/) page?

**Comment by RaphaelMeudec** [comment]
I'll add them in a PR during this week. For the tabletalks, I can see them fine, which browser are you using?

**Comment by rgbayrak** [comment]
Goggle chrome, firefox does not work, safari does.

**Comment by rgbayrak** [comment]
@RaphaelMeudec Sorry I see my description above might not have been clear. The comparison is divided in 15 mins blocks, makes it easier to find in the calendar if it is overlapping with something or not. Color coding is also very helpful. While avoiding a static schedule, I don't want to miss out on those features. So, currently I am thinking on keeping the static schedule and maybe adding those links to the panel and emergent session pages. If you have a little bit more time to help out with this, I am happy to do a quick Zoom chat. Thank you.

**Comment by rgbayrak** [comment]
Re: I have chatted with the group, I am merging this with things to do:

- add emergent session booking links
- eventually add emergent session info and streaming links
- add to calendar buttons for all events
- I think if we are keeping this design, we will remove the OHBM comparison part (I will do this shortly) 

@RaphaelMeudec thank you for putting this together, let me know if you can help with above items.
