### ISSUE TITLE
virtual events missing from the schedule

### ISSUE THREAD

**Issue by vborghe** [ohbm/osr2022#22]
poster pal is missing from the [schedule](https://ohbm.github.io/osr2022/schedule/) and might deserve a page as the rest of the program, what do you think @rgbayrak ?

**Comment by rgbayrak** [comment]
You mean a tab? or just added to the program excel sheet?

**Comment by vborghe** [comment]
Yeah, I think from 1/2 before until the end of the poster sessions is great! thanks!
