### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by rgbayrak** [ohbm/osr2022#6]
We need a search bar for the educational tab, where people can input a keyword or topic and search relevant educational videos within this page.

**Comment by rgbayrak** [comment]
@RaphaelMeudec any updates on this?

**Comment by RaphaelMeudec** [comment]
I should be able to work on it tomorrow!

**Comment by rgbayrak** [comment]
Fantastic thank you @RaphaelMeudec!! Can you give me an approximate date that you are hoping to send in your PR?

**Comment by RaphaelMeudec** [comment]
I think we can close this issue?
