### ISSUE TITLE
Main page header

### ISSUE THREAD

**Issue by rgbayrak** [ohbm/osr2022#7]
There is some resizing issue with the main page header, regardless of the size of window, the image should be visible. Need a fix for that.

**Comment by RaphaelMeudec** [comment]
The issue is a bit unclear to me: is it that the image is slightly cropped by the menu bar? I can't find resolutions where the image totally disappears.

**Comment by rgbayrak** [comment]
I meant the image should be fully visible. It does not disappear, it gets cropped rather than proportionally shrinking with the size of the window. At least on google chrome.
